config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:new]
  resources :albums, :artists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :albums, only: [:show]
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/views/pages/_alert.html.erb
<% unless notice.nil? %>
    <script>
        function remove_alert() {
            var alert = document.getElementById('ALERT');
            alert.remove();
        }
    </script>
    <div class="container py-3" id="ALERT">
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <%= notice %>
            <button type="button" class="btn-close" onClick="remove_alert()"></button>
        </div>
    </div>
<% end %>

app/views/pages/_footer.html.erb
<footer class="py-3 my-4">
  <ul class="nav justify-content-center border-bottom pb-3 mb-3">
    <li class="nav-item"><a href="/about" class="nav-link px-2 text-muted">About</a></li>
    <li class="nav-item"><a href="/contact" class="nav-link px-2 text-muted">Contact</a></li>
  </ul>
  <p class="text-center text-muted">© 2022 Music Collection App, Inc</p>
</footer>

app/views/pages/_navbar.html.erb
<nav class="navbar sticky-top navbar-expanded-lg bg-dark">
    <div class="container">
        <div class="d-flex align-left">
            <tr class="d-flex list-inline">
                <td class="list-inline-item"><a href="/" class="btn btn-dark text-light fs-5">Home</a></td>
                <td class="list-inline-item"><a href="/users" class="btn btn-dark text-light fs-5">Users</a></td>
                <td class="list-inline-item"><a href="/artists" class="btn btn-dark text-light fs-5">Artists</a></td>
                <td class="list-inline-item"><a href="/albums" class="btn btn-dark text-light fs-5">Albums</a></td>
            </tr>
        </div>
        <div class="d-flex align-right align-items-center">

            <% if logged_in? %>
                <%= link_to "#{current_user.first_name} (#{current_user.username})", user_path(current_user), class: "nav-link text-light m-2" %>
                <%= link_to 'Log out', logout_path, class: "nav-link text-light m-2", data: { "turbo-method": :delete } %>
            <% else %>
                <a href="/login" class="btn btn-light text-dark">Log in</a>
                <span class="text-light fw-light m-2">or</span>
                <a class="text-primary ", href="/signup">Sign up</a>
            <% end %>
        </div>
    </div>
</nav>

app/views/pages/about.html.erb
<div class="py-3"></div>
<h1 class="h1 fw-light text-center mt-4 py-5" style="font-size: 5em">
    Music Collection App <span class="fs-4 text-muted align-top">©</span>
</h1>
<div class="py-3"></div>

<div class="d-flex fs-3 fw-light container-fluid justify-content-center">
  <span class="text-center">The most comprehensive music collection app.</span>
</div>

<div class="py-5"></div>

<div class="d-flex fs-3 fw-light container-fluid justify-content-center">
  <span class="text-center">Developed by Carlos Xavier da Silveira.</span>
</div>

<div class="py-5"></div>

<div class="d-flex fs-3 fw-light container-fluid justify-content-center">
  <a href="https://github.com/CarlosXav" class="link link-primary" style="text-decoration: none">
    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-github m-1" viewBox="0 0 16 16">
        <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
    </svg>
    CarlosXav
  </a>
</div>

<div class="py-2"></div>

<div class="d-flex fs-3 fw-light container-fluid justify-content-center">
  <a href="https://www.linkedin.com/in/cesxs/" class="link link-primary" style="text-decoration: none">
    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-linkedin m-1" viewBox="0 0 16 16">
        <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
    </svg>
    cesxs
  </a>
</div>

app/views/pages/contact.html.erb
<div class="py-3"></div>
<h1 class="h1 fw-light text-center mt-4 py-5" style="font-size: 5em">
    Music Collection App <span class="fs-4 text-muted align-top">©</span>
</h1>
<div class="py-3"></div>

<div class="d-flex fs-3 fw-light container-fluid justify-content-center">
  <span class="text-center">The most comprehensive music collection app.</span>
</div>

<div class="py-5"></div>

<div class="d-flex fs-3 fw-light container-fluid justify-content-center">
  <span class="text-center">You contact us following the link below.</span>
</div>

<div class="py-5"></div>

<div class="d-flex fs-3 fw-light container-fluid justify-content-center">
  <a href="mailto:carlos.ed.sxs@gmail.com" class="link link-primary" style="text-decoration: none">
    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-envelope m-1" viewBox="0 0 16 16">
  <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z"/>
</svg>
    Email
  </a>
</div>

app/views/pages/home.html.erb
<div class="py-3"></div>
<h1 class="h1 fw-light text-center mt-4 py-5" style="font-size: 5em">
    Music Collection App <span class="fs-4 text-muted align-top">©</span>
</h1>
<div class="py-3"></div>

<div class="d-flex fs-3 fw-light container-fluid justify-content-center">
  <span class="text-center">The most comprehensive music collection app.</span>
</div>

<div class="py-5"></div>
<div class="container-fluid py-4 shadow-lg text-bg-dark">
  <div class="py-3"></div>
  <div class="container">
    <div class="row align-items-start justify-content-center align-items-center">
      <div class="col text-end">
        <span class="fs-3 fw-light p-3">Sign up today and gain access to our comprehensive database.</span>
        <div class="py-3"></div>
        <a class="btn btn-outline-light btn-lg fs-2" href="/signup">Sign up</a>
      </div>
      <div class="d-flex col-1 justify-content-center" style="height: 200px;">
        <div class="vr"></div>
      </div>
      <div class="col text-start fs-1 fw-light">
        <span>Free. <br>Fast. <br>Simple.</span>
      </div>
    </div>
  </div>

  <div class="py-3"></div>

</div>