config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:new]
  resources :albums, :artists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :albums, only: [:show]
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  validates :name, presence: true, length: {minimum: 1, maximum: 100}
  validates :artist, presence: true, length: {minimum: 1, maximum: 100}
  validates :description, length: {minimum: 0, maximum: 300}
  validates :user_id, presence: true, numericality: { only_integer: true }
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_login, :setup_artist_list
  before_action :set_album, only: %i[ show edit update destroy ]
  before_action :set_user, only: %i[ edit update show destory]
  before_action :require_admin, only: %i[ destroy ]
  before_action :require_self_or_admin, only: %i[ edit update ]
  before_action :setup_artist_list_for_dropdown_list, only: %i[ new edit ]
  
  # GET /albums or /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1 or /albums/1.json
  def show
    @album = Album.find(params[:id])
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit

  end

  # POST /albums or /albums.json
  def create
    @album = Album.new(album_params)
    @album.user = current_user
    respond_to do |format|
      if @album.save
        format.html { redirect_to album_url(@album), notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to album_url(@album), notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    def set_user
      @user = Album.find(params[:id]).user
      p "user: #{@user.to_s}, current_user: #{current_user.to_s}"
    end

    def setup_artist_list_for_dropdown_list
      artist_list = get_artist_list(0)
      @artists = {}
      artist_list.each do |artist| 
        @artists[artist['name']] = artist['id']
      end
    end

    def setup_artist_list
      @artists = get_artist_list(0)
    end
    

    # Only allow a list of trusted parameters through.
    def album_params
      album_params = params.require(:album).permit(:name, :artist, :description, :year, :user_id)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_album.html.erb
<h1 class="text-center mt-4 h1">
  <%= album['name'] %>
</h1>

<div class="py-4"></div>

<div class="container d-flex justify-content-center h2 fw-light">
  <%= link_to "by #{@artists[album['artist'].to_i - 1]['name']}", "/artists/#{album['artist']}", style: 'text-decoration: none'%>
</div>

<div class="py-4"></div>

<% unless album['description'].nil? %>
  <div class="container d-flex justify-content-center fw-light col-3">
    <%= album['description'] %>
  </div>
<% end %>

<div class="py-4"></div>

<div class="text-center fw-light">
  Entry by 
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle m-1" viewBox="0 0 16 16">
    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
  </svg>
  <span>
    <%= link_to album.user['username'], "/users/#{album.user['id']}", style: 'text-decoration: none' %>
  </span>
</div>

<div class="py-4"></div>

app/views/albums/_form.html.erb
<%= form_with(model: @album, class: "shadow-lg p-3 mb-3 bg-body rounded container", local: true) do |form| %>
  <% if album.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% album.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <div class="row align-items-center">
      <div class="input-group mb-3">
        <%= form.label :name, class: "input-group-text text-light bg-secondary fw-bold shadow-sm", style: "width: 10rem" %>
        <%= form.text_field :name, placeholder: "The album name", class: "col-sm-10 form-control shadow-sm" %>
      </div>

      <div class="input-group mb-3">
        <%= form.label :artist, class: "input-group-text text-light bg-secondary fw-bold shadow-sm", style: "width: 10rem" %>
        <%= form.select( :artist, @artists, {include_blank: "Please choose."}, {class: "col-sm-10 form-select shadow-sm"}) %>
      </div>

      <div class="input-group mb-3">
        <%= form.label :description, class: "input-group-text text-light bg-secondary fw-bold shadow-sm", style: "width: 10rem" %>
        <%= form.text_area :description, placeholder: "Give a brief description of the album (optional)", maxlength: "300", class: "col-sm-10 form-control shadow-sm" %>
      </div>

      <div class="input-group mb-3">
        <%= form.label :year, class: "input-group-text text-light bg-secondary fw-bold shadow-sm", style: "width: 10rem" %>
        <%= form.select( :year, 2022.downto(1900), {include_blank: "Please choose."}, {class: "col-sm-10 form-select shadow-sm"}) %>
      </div>

      <div class="form-group mb-3 d-flex justify-content-center align-items-center">
        <%= form.submit(@album.new_record? ? "Create album" : "Update album", class: "shadow-sm btn btn-outline-dark btn-lg") %>
        
      </div>
    </div>
  </div>
<% end %>

app/views/albums/_list.html.erb
<div class="container rounded shadow-lg p-3">
    <% unless @albums.blank? %>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Name</th>
                    <th scope="col">Artist</th>
                    <th scope="col">Created by</th>
                    <th scope="col">Creation Date</th>
                </tr>
            </thead>
            <% for album in @albums %>
                <tr>
                    <th scope="row"><%= album['id']%></th>
                    <td><%= link_to album['name'], "albums/#{album['id']}" %></td>
                    <td><%= link_to @artists[album['artist'].to_i - 1]['name'], "/artists/#{album['artist'].to_i}"%></td>
                    <td><%= link_to album.user['username'], "/users/#{album.user['id']}"%></td>
                    <td><%= album['created_at'].strftime("%m/%d/%Y")%></td>
                </tr>            
            <% end %>
        </table>
    

    <% end %>
</div>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render "form", album: @album %>

<br>

<div>
  <%= link_to "Show this album", @album %> |
  <%= link_to "Back to albums", albums_path %>
</div>

app/views/albums/index.html.erb
<h1 class="text-center mt-4">Albums</h1>
<div class="py-4"></div>

<div class="container d-flex justify-content-end align-items-center">
    <a href="/albums/new" class="link link-success">
        Create New Album
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle-fill m-3" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
        </svg>
    </a>
</div>

<%= render "list"%>

app/views/albums/new.html.erb
<h1 class="text-center mt-4">Create a New Album Entry</h1>
<div class="py-4"></div>
<%= render "form", album: @album %>

<br>

app/views/albums/show.html.erb
<%= render "album", album: @album %>
  
<div class="container">
  <ul class="nav justify-content-center pb-3 mb-3">
    <% if (current_user == @album.user) || current_user.admin %>
      <li class="nav-item m-2"><%= link_to "Edit this album", edit_album_path(@album), class: "link-secondary" %></li>
    <% end %>
    <% if current_user.admin %>
      <li class="nav-item m-2"><%= link_to "Destroy this album", @user, data: { "turbo-method": :delete }, class: "link-danger" %></li>
    <% end %>
    
  </ul>
</div>